package com.ztune.libretune.core.tune

import android.content.Context
import android.net.Uri
import java.io.*
import java.util.Base64

/**
 * Serializes and deserializes [Tune] objects to/from TunerStudio MSQ files.
 *
 * The MSQ format is an INI-style text format with sections:
 * ```
 * ; Comment lines start with semicolons
 * [Signature]
 * signature = "Speeduino 2024.01"
 * iniFilename = "speeduino.ini"
 *
 * [Page0]
 * data = <base64 encoded page bytes>
 *
 * [Page1]
 * data = <base64 encoded page bytes>
 *
 * [ConstantValues]
 * reqFuel = 6.5
 * nCylinders = 4.0
 *
 * [TableValues]
 * veTable = 1.0,2.0,3.0|4.0,5.0,6.0
 *
 * [CurveValues]
 * dwellCurve = 3.0,3.5,4.0
 *
 * [ProjectInfo]
 * name = "My Tune"
 * description = "Stage 1"
 * notes = "Baseline before turbo install"
 * createdAt = 1700000000000
 * modifiedAt = 1700000000000
 *
 * [IniMetadata]
 * signature = "Speeduino 2024.01"
 * name = "Speeduino"
 * hash = "a1b2c3..."
 * specVersion = "3.64"
 * savedAt = "2024-01-15T10:30:00Z"
 * ```
 *
 * Page data is base64-encoded to survive the text-based INI transport.
 */
object TuneSerializer {
    const val FILE_EXTENSION = ".msq"

    // ---- Public API ----

    /**
     * Save a tune to the file at [uri].
     *
     * @param context Android context for content resolver access.
     * @param uri Destination URI (typically from a Storage Access Framework picker).
     * @param tune The tune to serialize.
     * @param pageData Raw page bytes keyed by page number. If empty, falls back
     *   to [Tune.pageData].
     */
    fun save(context: Context, uri: Uri, tune: Tune, pageData: Map<Int, ByteArray> = emptyMap()): Result<Unit> =
        runCatching {
            val pages = if (pageData.isNotEmpty()) pageData else tune.pageData
            val content = exportMsq(tune, pages)
            context.contentResolver.openOutputStream(uri)?.use { os ->
                os.write(content.toByteArray(Charsets.UTF_8))
                os.flush()
            } ?: throw IOException("Cannot open output stream for URI: $uri")
        }

    /**
     * Load a tune from the file at [uri].
     *
     * @param context Android context for content resolver access.
     * @param uri Source URI.
     * @return The deserialized [Tune], or a failure if parsing fails.
     */
    fun load(context: Context, uri: Uri): Result<Tune> = runCatching {
        val text = context.contentResolver.openInputStream(uri)?.use { `is` ->
            `is`.bufferedReader(Charsets.UTF_8).readText()
        } ?: throw IOException("Cannot open input stream for URI: $uri")
        importMsq(text).getOrThrow()
    }

    /**
     * Export a tune as an MSQ-format string.
     *
     * @param tune The tune to serialize.
     * @param pageData Raw page bytes keyed by page number.
     */
    fun exportMsq(tune: Tune, pageData: Map<Int, ByteArray>): String {
        val sb = StringBuilder()
        sb.appendLine("; LibreTune MSQ file")
        sb.appendLine("; Generated by ztune")
        sb.appendLine()

        // ---- [Signature] ----
        sb.appendLine("[Signature]")
        sb.appendLine("signature = \"${escapeValue(tune.iniMetadata.signature)}\"")
        sb.appendLine("iniFilename = \"${escapeValue(tune.iniMetadata.name)}\"")
        sb.appendLine()

        // ---- [IniMetadata] ----
        if (tune.iniMetadata != IniMetadata()) {
            sb.appendLine("[IniMetadata]")
            if (tune.iniMetadata.signature.isNotEmpty())
                sb.appendLine("signature = \"${escapeValue(tune.iniMetadata.signature)}\"")
            if (tune.iniMetadata.name.isNotEmpty())
                sb.appendLine("name = \"${escapeValue(tune.iniMetadata.name)}\"")
            if (tune.iniMetadata.hash.isNotEmpty())
                sb.appendLine("hash = \"${escapeValue(tune.iniMetadata.hash)}\"")
            if (tune.iniMetadata.specVersion.isNotEmpty())
                sb.appendLine("specVersion = \"${escapeValue(tune.iniMetadata.specVersion)}\"")
            if (tune.iniMetadata.savedAt.isNotEmpty())
                sb.appendLine("savedAt = \"${escapeValue(tune.iniMetadata.savedAt)}\"")
            sb.appendLine()
        }

        // ---- [PageN] sections ----
        for ((pageNum, data) in pageData.toSortedMap()) {
            sb.appendLine("[Page$pageNum]")
            sb.appendLine("data = ${encodePage(data)}")
            sb.appendLine()
        }

        // ---- [ConstantManifest] ----
        if (tune.constantManifest.isNotEmpty()) {
            sb.appendLine("[ConstantManifest]")
            for (entry in tune.constantManifest) {
                sb.appendLine("${entry.name} = ${entry.dataType},${entry.page},${entry.offset},${entry.scale},${entry.translate}")
            }
            sb.appendLine()
        }

        // ---- [ConstantValues] ----
        if (tune.constantValues.isNotEmpty()) {
            sb.appendLine("[ConstantValues]")
            for ((name, value) in tune.constantValues.toSortedMap()) {
                sb.appendLine("$name = $value")
            }
            sb.appendLine()
        }

        // ---- [TableValues] ----
        if (tune.tableValues.isNotEmpty()) {
            sb.appendLine("[TableValues]")
            for ((name, table) in tune.tableValues.toSortedMap()) {
                val rows = table.joinToString("|") { row ->
                    row.joinToString(",") { cell ->
                        formatDouble(cell)
                    }
                }
                sb.appendLine("$name = $rows")
            }
            sb.appendLine()
        }

        // ---- [CurveValues] ----
        if (tune.curveValues.isNotEmpty()) {
            sb.appendLine("[CurveValues]")
            for ((name, curve) in tune.curveValues.toSortedMap()) {
                val values = curve.joinToString(",") { formatDouble(it) }
                sb.appendLine("$name = $values")
            }
            sb.appendLine()
        }

        // ---- [ProjectInfo] ----
        tune.projectInfo?.let { info ->
            sb.appendLine("[ProjectInfo]")
            if (info.name.isNotEmpty())
                sb.appendLine("name = \"${escapeValue(info.name)}\"")
            if (info.description.isNotEmpty())
                sb.appendLine("description = \"${escapeValue(info.description)}\"")
            if (info.notes.isNotEmpty())
                sb.appendLine("notes = \"${escapeValue(info.notes)}\"")
            sb.appendLine("createdAt = ${info.createdAt}")
            sb.appendLine("modifiedAt = ${info.modifiedAt}")
            sb.appendLine()
        }

        return sb.toString()
    }

    /**
     * Import a tune from an MSQ-format string.
     *
     * @param content The full text of the MSQ file.
     * @return The parsed [Tune], or a failure with a descriptive message.
     */
    fun importMsq(content: String): Result<Tune> = runCatching {
        val lines = content.lines()
        val sections = parseSections(lines)

        // Parse INI metadata from both [Signature] and [IniMetadata]
        val iniMetadata = parseIniMetadata(sections)

        // Parse page data
        val pageData = mutableMapOf<Int, ByteArray>()
        val pageRegex = Regex("^Page(\\d+)$")
        for ((sectionName, entries) in sections) {
            val match = pageRegex.matchEntire(sectionName) ?: continue
            val pageNum = match.groupValues[1].toInt()
            val encoded = entries["data"]
                ?: continue
            pageData[pageNum] = decodePage(encoded)
        }

        // Parse constant manifest
        val constantManifest = parseConstantManifest(sections["ConstantManifest"])

        // Parse constant values
        val constantValues = mutableMapOf<String, Double>()
        for ((key, raw) in (sections["ConstantValues"] ?: emptyMap())) {
            constantValues[key] = raw.toDoubleOrNull() ?: continue
        }

        // Parse table values
        val tableValues = mutableMapOf<String, List<List<Double>>>()
        for ((key, raw) in (sections["TableValues"] ?: emptyMap())) {
            val table = raw.split("|").map { rowStr ->
                rowStr.split(",").mapNotNull { it.trim().toDoubleOrNull() }
            }
            if (table.isNotEmpty() && table.any { it.isNotEmpty() }) {
                tableValues[key] = table
            }
        }

        // Parse curve values
        val curveValues = mutableMapOf<String, List<Double>>()
        for ((key, raw) in (sections["CurveValues"] ?: emptyMap())) {
            val curve = raw.split(",").mapNotNull { it.trim().toDoubleOrNull() }
            if (curve.isNotEmpty()) {
                curveValues[key] = curve
            }
        }

        // Parse project info
        val projectInfo = parseProjectInfo(sections["ProjectInfo"])

        Tune(
            iniMetadata = iniMetadata,
            constantManifest = constantManifest,
            pageData = pageData,
            constantValues = constantValues,
            tableValues = tableValues,
            curveValues = curveValues,
            projectInfo = projectInfo
        )
    }

    // ---- Base64 page encoding/decoding ----

    /**
     * Encode raw page bytes to a base64 string (URL-safe, no padding).
     */
    private fun encodePage(data: ByteArray): String =
        Base64.getEncoder().encodeToString(data)

    /**
     * Decode a base64 string back to raw page bytes.
     * Supports both standard and URL-safe base64.
     */
    private fun decodePage(encoded: String): ByteArray {
        val trimmed = encoded.trim()
        return try {
            Base64.getDecoder().decode(trimmed)
        } catch (_: IllegalArgumentException) {
            // Try URL-safe decoder as fallback
            Base64.getUrlDecoder().decode(trimmed)
        }
    }

    // ---- INI parsing helpers ----

    /**
     * Parse the text into a map of section name -> (key -> value).
     * Comments (lines starting with `;` or `#`) and blank lines are skipped.
     */
    private fun parseSections(lines: List<String>): Map<String, Map<String, String>> {
        val sections = mutableMapOf<String, MutableMap<String, String>>()
        var currentSection: String? = null

        for (line in lines) {
            val trimmed = line.trim()

            // Skip blank lines and comments
            if (trimmed.isEmpty() || trimmed.startsWith(";") || trimmed.startsWith("#"))
                continue

            // Section header: [SectionName]
            if (trimmed.startsWith("[") && trimmed.endsWith("]")) {
                currentSection = trimmed.substring(1, trimmed.length - 1).trim()
                sections.getOrPut(currentSection) { mutableMapOf() }
                continue
            }

            // Key = Value
            val eqIdx = trimmed.indexOf('=')
            if (eqIdx < 0 || currentSection == null)
                continue

            val key = trimmed.substring(0, eqIdx).trim()
            val value = trimmed.substring(eqIdx + 1).trim()
            // Strip surrounding quotes from value
            val unquoted = unquote(value)
            sections[currentSection]!![key] = unquoted
        }

        return sections
    }

    /** Remove surrounding double quotes from a string, if present. */
    private fun unquote(value: String): String {
        if (value.length >= 2 && value.startsWith("\"") && value.endsWith("\"")) {
            return value.substring(1, value.length - 1)
        }
        return value
    }

    /**
     * Parse [IniMetadata] from the [Signature] and [IniMetadata] sections.
     */
    private fun parseIniMetadata(sections: Map<String, Map<String, String>>): IniMetadata {
        val sig = sections["Signature"]
        val meta = sections["IniMetadata"]

        // Signature section provides signature and iniFilename (name)
        val signature = sig?.get("signature")
            ?: meta?.get("signature")
            ?: ""
        val name = sig?.get("iniFilename")
            ?: meta?.get("name")
            ?: ""

        return IniMetadata(
            signature = signature,
            name = name,
            hash = meta?.get("hash") ?: "",
            specVersion = meta?.get("specVersion") ?: "",
            savedAt = meta?.get("savedAt") ?: ""
        )
    }

    /**
     * Parse the [ConstantManifest] section entries.
     * Each line: name = dataType,page,offset,scale,translate
     */
    private fun parseConstantManifest(entries: Map<String, String>?): List<ConstantManifestEntry> {
        if (entries.isNullOrEmpty()) return emptyList()
        val result = mutableListOf<ConstantManifestEntry>()
        for ((name, raw) in entries) {
            val parts = raw.split(",")
            if (parts.size < 3) continue
            result.add(
                ConstantManifestEntry(
                    name = name,
                    dataType = parts[0].trim(),
                    page = parts[1].trim().toIntOrNull() ?: 0,
                    offset = parts[2].trim().toIntOrNull() ?: 0,
                    scale = parts.getOrNull(3)?.trim()?.toDoubleOrNull() ?: 1.0,
                    translate = parts.getOrNull(4)?.trim()?.toDoubleOrNull() ?: 0.0
                )
            )
        }
        return result
    }

    /**
     * Parse [ProjectInfo] from its section entries.
     */
    private fun parseProjectInfo(entries: Map<String, String>?): ProjectInfo? {
        if (entries.isNullOrEmpty()) return null
        return ProjectInfo(
            name = entries["name"] ?: "",
            description = entries["description"] ?: "",
            createdAt = entries["createdAt"]?.toLongOrNull() ?: System.currentTimeMillis(),
            modifiedAt = entries["modifiedAt"]?.toLongOrNull() ?: System.currentTimeMillis(),
            notes = entries["notes"] ?: ""
        )
    }

    // ---- Formatting helpers ----

    /**
     * Escape a string value for safe inclusion inside double quotes in the MSQ file.
     * Backslashes and double-quotes are escaped.
     */
    private fun escapeValue(value: String): String =
        value.replace("\\", "\\\\").replace("\"", "\\\"")

    /**
     * Format a double value for the MSQ file.
     * Uses a fixed number of decimal places to avoid floating-point noise,
     * but preserves precision for very small or very large values.
     */
    private fun formatDouble(value: Double): String {
        val formatted = "%.10g".format(value)
        // Ensure we don't produce unnecessarily long representations
        return when {
            formatted.contains('.') || formatted.contains('e') || formatted.contains('E') -> formatted
            else -> "${formatted}.0"
        }
    }
}